# Generated by Django 3.0.3 on 2020-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20200404_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.TextField(default='0000000000', max_length=10),
        ),
    ]
