# Generated by Django 3.0.3 on 2020-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_userinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='url_id',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.TextField(default='', max_length=10),
        ),
    ]
