# Generated by Django 3.0.3 on 2020-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20200411_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='url_id',
            field=models.CharField(default='', max_length=7),
        ),
    ]
