# Generated by Django 3.0.3 on 2020-04-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20200411_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='url_id',
        ),
    ]
