# Generated by Django 3.0.3 on 2020-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_userinfo_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
