# Generated by Django 3.0.3 on 2020-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_auto_20200411_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='visits_counter',
            field=models.IntegerField(default=0),
        ),
    ]
