# Generated by Django 3.0.3 on 2020-04-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_userinfo_visits_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='unsubscribe',
            field=models.BooleanField(default=0),
        ),
    ]
