# Generated by Django 3.0.3 on 2020-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0011_auto_20200413_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
